INSERT INTO users (name, age) VALUES ("David", 28);
INSERT INTO users (name, age) VALUES ("Brian", 28);
INSERT INTO users (name, age) VALUES ("Bo", 28);
INSERT INTO users (name, age) VALUES ("Jill", 28);
INSERT INTO users (name, age) VALUES ("Bri", 28);
INSERT INTO users (name, age) VALUES ("JJ", 28);
INSERT INTO users (name, age) VALUES ("DJ", 28);
INSERT INTO users (name, age) VALUES ("PJ", 28);
INSERT INTO users (name, age) VALUES ("Ronnie", 28);
INSERT INTO users (name, age) VALUES ("Wes", 28);
INSERT INTO users (name, age) VALUES ("Andy", 28);
INSERT INTO users (name, age) VALUES ("Lola", 28);
INSERT INTO users (name, age) VALUES ("Jim", 28);
INSERT INTO users (name, age) VALUES ("Joe", 28);
INSERT INTO users (name, age) VALUES ("Rhonda", 28);
INSERT INTO users (name, age) VALUES ("Rhianna", 28);
INSERT INTO users (name, age) VALUES ("Yeezy", 28);
INSERT INTO users (name, age) VALUES ("Kanye", 28);
INSERT INTO users (name, age) VALUES ("Pat", 20);
INSERT INTO users (name, age) VALUES ("Reid", 8);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("One", "WIN", 100, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Two", "WIN", 500, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Three", "WIN", 400, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Four", "WIN", 200, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Five", "WIN", 100, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Six", "WIN", 20, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Seven", "L", 125, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eight", "L", 225, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Nine", "L", 888, "1/21/21", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ten", "L", 1000, "1/21/21", "2/21/21");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 10, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 18, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (555, 20, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (124, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (88, 15, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (185, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (352, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 19, 7);
